name: Build and deploy Node.js app to Azure Web App - dev-pids-ams-wa

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Prepare Standalone Deploy
        run: |
          rm -rf deploy
          mkdir -p deploy

          echo "Copying standalone build..."
          cp -r .next/standalone/. deploy/

          echo "Copying static files..."
          mkdir -p deploy/.next
          cp -r .next/static deploy/.next/static

          echo "Copying public folder..."
          cp -r public deploy/public

          echo "Copying Prisma folder..."
          cp -r prisma deploy/prisma

          # Add BUILD_ID
          cp -r .next/BUILD_ID deploy/.next/

      - name: Zip artifact for deployment
        run: |
          cd deploy
          zip -r ../deploy.zip .
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: pids-alarm-management-system
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: pids-alarm-management-system

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2C533481B4E24CF6948B9802FF52B62F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7DCA478838824C94833A4F8FB83C150C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2481ED2D7B924127A0D825558A5AD445 }}

      - name: Configure Web App Settings
        run: |
          RG=$(az webapp list --query "[?name=='dev-pids-ams-wa'].resourceGroup" -o tsv)

          az webapp config appsettings set \
            --name dev-pids-ams-wa \
            --resource-group "$RG" \
            --settings \
              DATABASE_URL="${{ secrets.DEV_DATABASE_URL }}" \
              NEXTAUTH_SECRET="${{ secrets.DEV_NEXTAUTH_SECRET }}" \
              NEXTAUTH_URL="${{ secrets.DEV_NEXTAUTH_URL }}" \
              AUTH_TRUST_HOST="${{ secrets.DEV_AUTH_TRUST_HOST }}" \

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "dev-pids-ams-wa"
          slot-name: "Production"
          package: deploy.zip
